language: node_js
node_js:
  - 6.2.0
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm install -g bower gulp
  - gem install sass
  - bower install
services:
  - redis-server
